# NOME | SOBRENOME | DATA DE NASCIMENTO | ALTURA | PESO

user = ['Lucas', 'Oliveira', '12/12/1995', '1.75', '87']

print('='*100)
# BUSCA O PRIMEIRO ITEM DA LISTA
print(user[0])

print('='*100)
# BUSCA O ÚLTIMO ITEM DA LISTA
print(user[-1])

print('='*100)
# BUSCA O UM ITEM ALEATORIO DA LISTA
print(user[2]) #AQUI NO CASO ELE ESTARIA TRAZENDO A DATA DE NASCIMENTO
print(user[0:2]) #AQUI NO CASO ELE ESTARIA TRAZENDO O NOME E O SOBRENOME